/* Main.c file generated by New Project wizard
 * Author: EWODO Pierre Bertried
 * Created:   lun. jan. 9 2022
 * Processor: PIC16F887
 * Compiler:  HI-TECH C for PIC10/12/16
 */

#include <htc.h>
#include <pic.h>
#include "lcd.h"

#define XTAL_FREQ 20000000

__CONFIG(FOSC_HS& WDTE_OFF& PWRTE_OFF& MCLRE_ON& CP_OFF& LVP_OFF);

unsigned char sec = 0, mins = 0, heure = 0, h = 0;
typedef enum { LUN, MAR, MER, JEU, VEN, SAM, DIM }Jour; //Définition d'un type Jour pour faciliter la lecture/écriture du code
Jour j = LUN;  // Début de la semaine (affichage à partir de lundi)
const char* jours[7] = { "LUN","MAR","MER","JEU","VEN","SAM","DIM" };
char Time[] = "00:00:00 AM"; //Début de l'affichage de l'heure


bit antirebond(char c) { //Sous-programme antirebond pour éviter les rebonds lorsqu'un bouton est appuyé
    char count = 0, i = 0;
    for (; i < 5; i++) {
        switch(c){// Déterminer quel bouton a été appuyé
            case 'm':if (RB1 == 0)count++; 
                break;
            case 'h':if (RB2 == 0)count++;
                break;
            case 'j':if (RB3 == 0)count++;
                break;
        }
        delay_ms(10);
    }
    if (count > 2)  return 1;//Si le bouton est toujours appuyé
    else  return 0; //Si le bouton est relaché 
}

// ---- Sous-programme du réglage de l'heure -----//
void lire_heure() { 
    delay_ms(1000); // Temporisation 1000 ms (une seconde)
    ++sec;          //Incrémenter sec par 1
    mins += sec / 60; //Incrémenter mins par 1 si sec == 60
    if (!RB1){      // Si le bouton minute est appuyé
        while(antirebond('m'));//Attendre que le bouton minute soit relaché
        mins++;     //Incrémenter mins par 1
    }
    h += mins / 60; //Incrémenter h par 1 si mins == 60
    if (!RB2){      // Si le bouton heure est appuyé
        while(antirebond('h'));//Attendre que le bouton heure soit relaché
        h++;        //Incrémenter h par 1
    }
    j = (j + (h / 24)) % 7; //Incrémenter j par 1 si h == 24 et faire un cycle de 7jours
    if (!RB3){      // Si le bouton jour est appuyé
        while(antirebond('j'));//Attendre que le bouton jour soit relaché
        j++;        //Incrémenter j par 1
    }
    h %= 24;    //Réinitialiser h lorsque h == 24
    mins %= 60; //Réinitialiser mins lorsque mins == 60
    sec %= 60;  //Réinitialiser sec lorsque sec == 60
    heure = h;  //Mettre h dans la variable heure qui sera utilisée pour afficher l'heure au format AM/PM (jour/nuit)
    heure = heure < 13 ? heure : ++heure % 13; //heure € [0,12] de minuit à midi et heure € [1,11] de 13hr à 23hr
    Time[0] = heure / 10 + '0';   //Changer la dizaine de heure en char 
    Time[1] = heure % 10 + '0';   //Changer l'unité de heure en char
    Time[3] = mins / 10 + '0';    //Changer les dizaines de mins en char
    Time[4] = mins % 10 + '0';    //Changer les unités de mins en char
    Time[6] = sec / 10 + '0';     //Changer les dizaines de sec en char
    Time[7] = sec % 10 + '0';     //Changer les unités de sec en char
    Time[9] = h < 12 ? 'A' : 'P' ;//Basculement de mode lorsque h >= 12  (AM => PM)
}


//-------- Sous-programme de l'affichage ---------//
void affichage() {
    if (!RB0) {  // Enclancher l'affichage de l'heure 
        // Condition pour que toutes les LEDs s'allument à midi et à minuit
        if (((heure == mins) && (mins == sec) && (sec == 0)) || (heure == 12 && (mins == sec) && (sec == 0))){
            PORTA = PORTC = 0x3F;   //Allumer toutes les LEDs
            delay_ms(2000);         //Temporisaion 2 secs
            sec += 2;               //Incrémenter secs par 2
        }
        lire_heure(); 
        PORTA = heure < 6 || heure == 12 ? 1 << heure % 12 : 0; //
        PORTC = heure < 6 ? 0 : 1 << (heure - 6);
        lcd_set_cursor(1, 1);
        lcd_write_string(jours[j]);             //Afficher le jour
        lcd_set_cursor(1, 5);
        lcd_write_string(Time);                 //Afficher l'heure
        lcd_set_cursor(2, 1);
        lcd_write_string("Lion ");              //Afficher le numéro du lion
        lcd_write_character(heure / 10 + '0');
        lcd_write_character(heure % 10 + '0');
    }
    else { // Stopper l'affichage de l'heure
        PORTA = 0x00;
        PORTC = 0x00;
        lcd_clear();
        delay_ms(5);
        lcd_set_cursor(1,1);
        lcd_write_string("           Cour des Lions");
        for(int a = 0 ;a < 32;a++){
        lcd_shift_left();
        delay_ms(1000);}
        lcd_clear();
    }
}

//++++++++ Programme Principale ++++++++//
void main() {
    ANSEL = 0;                      //Desactiver l'entrée analogique du PORTA
    ANSELH = 0;                     //Desactiver l'entrée analogique du PORTB
    TRISA = TRISC = TRISD = 0xC0;
    nRBPU = 0;                      //Activater les résistances pull-up du PORTB
    WPUB = 0x0F;                    //Connecter des entrées RB0-RB3 aux résistances pull-up
    PORTA = PORTC = 0;
    lcd_init();                     //Initialiser l'afficheur LCD
    while (1) {
        affichage();
    }
}